// AZ-wave: seed events for admin calendar week-grid view.
// Days are 0–6 (Sun..Sat). Hours are 24h clock. Keep dayOfWeek spread so
// the week visual shows multiple columns at first load.

import type { CalendarEvent } from "./types";

export const SEED_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: "ev-1",
    title: "Acme — Steering committee",
    clientId: "cl-1",
    projectId: "pr-1",
    kind: "session",
    dayOfWeek: 1,
    hour: 9,
    durationHours: 2,
    location: "Zoom",
    notes: "Review Phase 2 progress. Bawa value-stream map terbaru.",
  },
  {
    id: "ev-2",
    title: "Foobar — Discovery call",
    clientId: "cl-2",
    kind: "session",
    dayOfWeek: 1,
    hour: 14,
    durationHours: 1,
    location: "Zoom",
    notes: "Probe pain-point GTM, hint workshop format.",
  },
  {
    id: "ev-3",
    title: "Internal — Sprint planning",
    kind: "internal",
    dayOfWeek: 2,
    hour: 10,
    durationHours: 1,
    location: "SCBD Office",
  },
  {
    id: "ev-4",
    title: "Acme — Plant visit Bekasi",
    clientId: "cl-1",
    projectId: "pr-1",
    kind: "session",
    dayOfWeek: 2,
    hour: 13,
    durationHours: 4,
    location: "Pabrik Bekasi",
    notes: "Gemba walk lini 2 & 3. Wawancara supervisor shift.",
  },
  {
    id: "ev-5",
    title: "Foobar — GTM Workshop Day 1",
    clientId: "cl-2",
    kind: "workshop",
    dayOfWeek: 3,
    hour: 9,
    durationHours: 6,
    location: "Hotel Aryaduta Bandung",
  },
  {
    id: "ev-6",
    title: "Foobar — GTM Workshop Day 2",
    clientId: "cl-2",
    kind: "workshop",
    dayOfWeek: 4,
    hour: 9,
    durationHours: 6,
    location: "Hotel Aryaduta Bandung",
  },
  {
    id: "ev-7",
    title: "Deadline — INV-2026-002 jatuh tempo",
    clientId: "cl-1",
    kind: "deadline",
    dayOfWeek: 4,
    hour: 17,
    durationHours: 1,
    location: "—",
  },
  {
    id: "ev-8",
    title: "Acme — Weekly memo review",
    clientId: "cl-1",
    projectId: "pr-1",
    kind: "session",
    dayOfWeek: 5,
    hour: 10,
    durationHours: 1,
    location: "Zoom",
  },
  {
    id: "ev-9",
    title: "Beta Labs — Follow-up call",
    clientId: "cl-3",
    kind: "session",
    dayOfWeek: 5,
    hour: 15,
    durationHours: 1,
    location: "Zoom",
    notes: "Discuss retainer extension Q3.",
  },
  {
    id: "ev-10",
    title: "Internal — Knowledge base writing",
    kind: "internal",
    dayOfWeek: 5,
    hour: 16,
    durationHours: 2,
    location: "Async",
  },
  {
    id: "ev-11",
    title: "Deadline — Phase 2 deliverable Acme",
    clientId: "cl-1",
    projectId: "pr-1",
    kind: "deadline",
    dayOfWeek: 1,
    hour: 17,
    durationHours: 1,
    location: "—",
  },
  {
    id: "ev-12",
    title: "Networking — IDX Consulting Summit",
    kind: "internal",
    dayOfWeek: 6,
    hour: 9,
    durationHours: 4,
    location: "Ritz-Carlton Pacific Place",
  },
  {
    id: "ev-13",
    title: "Foobar — Workshop debrief",
    clientId: "cl-2",
    kind: "session",
    dayOfWeek: 0,
    hour: 19,
    durationHours: 1,
    location: "Zoom",
  },
  {
    id: "ev-14",
    title: "Acme — Mid-week sync",
    clientId: "cl-1",
    projectId: "pr-1",
    kind: "session",
    dayOfWeek: 3,
    hour: 16,
    durationHours: 1,
    location: "Zoom",
  },
];
